[[main]]
  identifier = "home"
  name = "Home"
  pre = '<i class="fas fa-home me-1"></i>'
  weight = 1
  url = "https://hbs.razonyang.com/"
[[main]]
  identifier = "blog"
  name = "Blog"
  pre = '<i class="fas fa-fw fa-blog me-1"></i>'
  weight = 2
[[main]]
  name = "Support"
  identifier = "support"
  pre = '<i class="fas fa-fw fa-info-circle me-1"></i>'
  weight = 40
[[main]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  pre = '<i class="fab fa-fw fa-github me-1"></i>'
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
[[main]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  pre = '<i class="fas fa-fw fa-comments me-1"></i>'
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
[[main]]
  name = "Features Request"
  identifier = "feature-request"
  pre = '<i class="fas fa-fw fa-lightbulb me-1"></i>'
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.yml"
  weight = 3
[[main]]
  name = "Bug Report"
  identifier = "bug-report"
  parent = "support"
  pre = '<i class="fas fa-fw fa-bug me-1"></i>'
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.yml"
  weight = 3
[[main]]
  parent = "support"
  weight = 4
  [main.params]
    divider = true

[[footer]]
  name = "Support"
  identifier = "support"
  weight = 1
[[footer]]
  name = "Repository"
  identifier = "repository"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap"
  weight = 1
  pre = '<i class="fab fa-fw fa-github me-1"></i>'
[[footer]]
  name = "Discussions"
  identifier = "discussions"
  parent = "support"
  url = "https://github.com/razonyang/hugo-theme-bootstrap/discussions/new"
  weight = 2
  pre = '<i class="fas fa-fw fa-comments me-1"></i>'
[[footer]]
  name = "Features Request"
  identifier = "feature-request"
  parent = "support"
  pre = '<i class="fas fa-fw fa-lightbulb me-1"></i>'
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.md"
  weight = 3
[[footer]]
  name = "Bug Report"
  identifier = "bug-report"
  parent = "support"
  pre = '<i class="fas fa-fw fa-bug me-1"></i>'
  url = "https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.md"
  weight = 4

[[footer]]
  name = "Docs"
  identifier = "docs"
  weight = 2

[[footer]]
  name = "Features"
  identifier = "features"
  weight = 3

[[footer]]
  identifier = "demo"
  name = "Demo"
  weight = 4
[[footer]]
  identifier = "demo-netlify"
  parent = "demo"
  name = "Netlify"
  weight = 1
  url = "https://hbs.razonyang.com"
[[footer]]
  identifier = "demo-china"
  parent = "demo"
  name = "China"
  weight = 2
  url = "https://hbs-cn.razonyang.com"
